name: "Build and push docker image"

on:
  push:
    branches: [ main ]

jobs:

  build:
  
    runs-on: ubuntu-latest
    
    steps:

    - uses: actions/checkout@v4

    - name: Login to Docker Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.DOCKER_REGISTRY_NAMESPACE }}
        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
        
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ secrets.DOCKER_REGISTRY_NAMESPACE }}/metarisc-web:latest

  deploy:

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy container
        run: |
          curl -X POST \
            -H "X-Auth-Token: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}" \
            "https://api.scaleway.com/containers/v1beta1/regions/fr-par/containers/${{ secrets.SCALEWAY_CONTAINER_ID }}/deploy"